version: '3'
services: 
  web_1:
    build: ./web_1
    depends_on: 
      - db
    volumes: 
      - ./html/:/var/www/html/
      - ./web_1/default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports: 
      - "8005:80"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=db:3306
     - PMA_USER=root
     - PMA_PASSWORD=rootroot
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: preform
      MYSQL_USER: test
      MYSQL_PASSWORD: testtest
      MYSQL_ROOT_PASSWORD: rootroot
      TZ: Asia/Tokyo
    ports: 
      - "3306:3306"
    volumes: 
      - vue_laravel:/var/lib/mysql
volumes: 
  vue_laravel: {}